# Generated by Django 4.0.3 on 2022-04-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=200, null=True)),
                ('playlistID', models.CharField(max_length=200, null=True)),
                ('attr', models.CharField(max_length=50)),
                ('trackID_1', models.CharField(max_length=200)),
                ('trackID_2', models.CharField(max_length=200)),
            ],
        ),
    ]
