# Generated by Django 4.0.3 on 2022-04-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=200)),
                ('attr', models.CharField(max_length=50)),
                ('trackID_1', models.CharField(max_length=200)),
                ('trackID_2', models.CharField(max_length=200)),
                ('trackID_3', models.CharField(max_length=200)),
                ('trackID_4', models.CharField(max_length=200)),
                ('trackID_5', models.CharField(max_length=200)),
                ('trackID_6', models.CharField(max_length=200)),
                ('trackID_7', models.CharField(max_length=200)),
                ('trackID_8', models.CharField(max_length=200)),
                ('trackID_9', models.CharField(max_length=200)),
                ('trackID_10', models.CharField(max_length=200)),
            ],
        ),
    ]
