# Generated by Django 4.0.3 on 2022-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='trackID_10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='trackID_9',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='trackID_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='trackID_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
