# Generated by Django 4.0.3 on 2022-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='userEmail',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
