# Generated by Django 4.0.3 on 2022-03-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.IntegerField(unique=True)),
                ('trackID', models.IntegerField(max_length=50, unique=True)),
                ('loudness', models.IntegerField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('mood', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('custom_attr1', models.CharField(max_length=200)),
                ('custom_attr2', models.CharField(max_length=200)),
                ('custom_attr3', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('userEmail', 'trackID')},
            },
        ),
    ]
