# Generated by Django 4.0.3 on 2022-03-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
